name: ci-go-workflow
on: [push]
jobs: 
  check-application:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.22'

      # - name: Install dependencies
      #   run: go mod download

      - name: Run tests
        run: go test
      
      - name: Run
        run: go run math.go

      # - name: Build application
      #   run: go build -o myapp ./cmd/myapp

      # - name: Upload build artifact
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: myapp